worker_processes 1;
worker_shutdown_timeout 5s;
pid /tmp/hello-vers-nginx/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 256;
}

http {
    access_log /dev/stdout;
    server_tokens off;
    client_body_temp_path /tmp/hello-vers-nginx/client;
    proxy_temp_path /tmp/hello-vers-nginx/proxy;
    fastcgi_temp_path /tmp/hello-vers-nginx/fastcgi;
    uwsgi_temp_path /tmp/hello-vers-nginx/uwsgi;
    scgi_temp_path /tmp/hello-vers-nginx/scgi;

    server {
        listen 8080;
        listen [::]:8080;
        server_name _;

        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}
